#!/bin/sh

heading () {
  echo "\n$(tput setaf 6)$1$(tput sgr0)"
}

heading "Upgrading system packages ..."
sudo apt update
sudo apt upgrade -y

heading "Installing essential packages ..."
sudo apt install -y bash-completion build-essential curl git wget

heading "Installing Node.js ..."
if [ ! -f "/etc/apt/sources.list.d/nodesource.list" ]; then
  curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
fi
sudo apt install -y nodejs

heading "Installing yarn ..."
if [ ! -f "/etc/apt/sources.list.d/yarn.list" ]; then
  curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  sudo apt update
fi
sudo apt install -y yarn

heading "Installing databases ..."
sudo apt install -y sqlite3 libsqlite3-dev
sudo apt install -y postgresql libpq-dev

heading "Installing Spacemacs ..."
sudo apt install -y emacs-nox hunspell silversearcher-ag --no-install-recommends
git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d
